# Generated by Django 5.1.6 on 2026-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_category_id_alter_matchresult_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
